### ISSUE TITLE
Can't download gem

### ISSUE THREAD

**Issue by vladiim** [buttercloud/tookan_ruby_api#1]
Not sure what's happening here - I'm not having luck being able to install the gem.

```
$ ruby -v
#=> ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```
***
### Direct install

```
$ gem install tookan_ruby_api
ERROR:  Could not find a valid gem 'tookan_ruby_api' (>= 0) in any repository
```
***
### Gemfile

```
# Gemfile
source 'https://rubygems.org'

ruby '2.5.1'
gem 'tookan_ruby_api'
```

```
$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'tookan_ruby_api' in any of the gem
sources listed in your Gemfile.
```

***
### Gemfile via Github

```
# Gemfile
gem 'tookan_ruby_api', git: 'git://github.com/buttercloud/tookan_ruby_api.git'
# Same happens with - gem 'tookan_ruby_api', git: "https://github.com/buttercloud/tookan_ruby_api.git"
```

```
$ bundle
Using tookan_ruby_api 0.1.1 from git://github.com/buttercloud/tookan_ruby_api.git (at master@8a80167)
$ irb
> require 'tookan_ruby_api'
Traceback (most recent call last):
       16: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/exe/bundle:22:in `<top (required)>'
       15: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
       14: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/exe/bundle:30:in `block in <top (required)>'
       13: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/cli.rb:18:in `start'
       12: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
       11: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/cli.rb:27:in `dispatch'
       10: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        9: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        8: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        7: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/cli.rb:424:in `exec'
        6: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/cli/exec.rb:28:in `run'
        5: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
        4: from /Users/vlad/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/cli/exec.rb:74:in `load'
        3: from /Users/vlad/.rbenv/versions/2.5.1/bin/irb:11:in `<top (required)>'
        2: from (irb):1
        1: from (irb):1:in `require'
LoadError (cannot load such file -- tookan_ruby_api)
```

**Comment by luaybs** [comment]
Hello @vladiim 

This project is still a WIP. I haven't published it on RubyGems yet. If you'd like to install it, you can use the `github` option in your Gemfile as such:

```
gem "tookan_ruby_api", github: "buttercloud/tookan_ruby_api"
```
